name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  image-build-and-push:
    name: Build and Sign Image
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/image-build-and-publish.yml

  publish-helm:
    name: Publish Helm Chart
    needs: [image-build-and-push]
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/helm-publish.yml
