name: Main build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  image-build-and-push:
    name: Build and Sign Image
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/image-build-and-publish.yml
